spring.application.name=MuviMatchr

spring.datasource.url=jdbc:postgresql://localhost:5432/muvimatchr
spring.datasource.username=muvimatchr
spring.datasource.password=muvimatchr
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
